version: "3"
services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass redispassword
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
  gateway:
    container_name: kwetter-gateway
    image: mrrrluiigii/kwetter-gateway
    environment:
      PORT_GATEWAY: ${PORT_GATEWAY}
      FRONTEND_HOST: ${FRONTEND_HOST}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      PROFILE_SERVICE_HOST: ${PROFILE_SERVICE_HOST}
      TREND_SERVICE_HOST: ${TREND_SERVICE_HOST}
      KWEET_SERVICE_HOST: ${KWEET_SERVICE_HOST}
      FOLLOW_SERVICE_HOST: ${FOLLOW_SERVICE_HOST}
      LIKE_SERVICE_HOST: ${LIKE_SERVICE_HOST}
    ports:
      - 3000:3000
  auth-service:
    container_name: kwetter-auth-service
    image: mrrrluiigii/kwetter-auth-service
    environment:
      PORT_AUTH: ${PORT_AUTH}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_DATABASE_AUTH: ${TYPEORM_DATABASE_AUTH}
    ports:
      - 3001:3001
    depends_on:
      - redis
  mail-service:
    container_name: kwetter-mail-service
    image: mrrrluiigii/kwetter-mail-service
    environment:
      PORT_MAIL: ${PORT_MAIL}
      SMTP_CONNECTION: ${SMTP_CONNECTION}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 3002:3002
    depends_on:
      - redis
  profile-service:
    container_name: kwetter-profile-service
    image: mrrrluiigii/kwetter-profile-service
    environment:
      PORT_PROFILE: ${PORT_PROFILE}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_DATABASE_PROFILE: ${TYPEORM_DATABASE_PROFILE}
    ports:
      - 3003:3003
    depends_on:
      - redis
  trend-service:
    container_name: kwetter-trend-service
    image: mrrrluiigii/kwetter-trend-service
    environment:
      PORT_TREND: ${PORT_TREND}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_DATABASE_TREND: ${TYPEORM_DATABASE_TREND}
    ports:
      - 3004:3004
    depends_on:
      - redis
  kweet-service:
    container_name: kwetter-kweet-service
    image: mrrrluiigii/kwetter-kweet-service
    environment:
      PORT_KWEET: ${PORT_KWEET}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_DATABASE_KWEET: ${TYPEORM_DATABASE_KWEET}
    ports:
      - 3005:3005
    depends_on:
      - redis
  follow-service:
    container_name: kwetter-follow-service
    image: mrrrluiigii/kwetter-follow-service
    environment:
      PORT_FOLLOW: ${PORT_FOLLOW}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_DATABASE_FOLLOW: ${TYPEORM_DATABASE_FOLLOW}
    ports:
      - 3006:3006
    depends_on:
      - redis
  like-service:
    container_name: kwetter-like-service
    image: mrrrluiigii/kwetter-like-service
    environment:
      PORT_LIKE: ${PORT_LIKE}
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      TYPEORM_DATABASE_LIKE: ${TYPEORM_DATABASE_LIKE}
    ports:
      - 3007:3007
    depends_on:
      - redis
